apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: quote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quote
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: quote
    spec:
      containers:
      - name: quote-pod
        image: vkoster/quote:v01
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000

