apiVersion: v1
kind: Service
metadata:
  name: quote-service
spec:
  type: LoadBalancer
  selector:
    app: quote
  ports:
  - port: 3000         # Service Port
    targetPort: 3000   # Container Port