apiVersion: v1
kind: Pod
metadata:
  name: quote-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: quote
    image: vkoster/quote:latest
    ports:
    - containerPort: 3000
    livenessProbe:
      httpGet:
        path: /
        port: 3000