apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvmongo
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /var/storage/mongodb
    server: 192.168.2.9
  persistentVolumeReclaimPolicy: Retain